name = "bbff-hmb-photo-site"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.development]
vars = { ENVIRONMENT = "development" }

[env.production]
vars = { ENVIRONMENT = "production" }

# R2 bucket binding for photo storage
[[env.production.r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "hmbbrew-25th-photos"

[[env.development.r2_buckets]]
binding = "PHOTOS_BUCKET"
bucket_name = "hmbbrew-25th-photos-dev"

# KV namespace for branding assets
[[env.production.kv_namespaces]]
binding = "BRANDING_ASSETS"
id = "YOUR_PRODUCTION_KV_ID"

[[env.development.kv_namespaces]]
binding = "BRANDING_ASSETS"
id = "YOUR_DEVELOPMENT_KV_ID"

# Analytics binding for monitoring
[[env.production.analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "bbff_photo_analytics"

# Environment-specific settings
[env.production.vars]
MAX_UPLOAD_SIZE = "10485760"  # 10MB
UPLOAD_RATE_LIMIT = "100"
CACHE_TTL = "604800"  # 7 days

[env.development.vars]
MAX_UPLOAD_SIZE = "5242880"   # 5MB for dev
UPLOAD_RATE_LIMIT = "20"
CACHE_TTL = "300"  # 5 minutes for dev